<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kunjungan_model_S extends CI_Model
{

    public $table = 'kunjungan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,tamu,jenis_tamu,waktu,foto,penerima_tamu,tujuan_kunjungan,no_hp_tamu,alamat_tamu,created_at,created_by,ket_tambahan');
        $this->datatables->from('kunjungan');
        //add this line for join
        //$this->datatables->join('table2', 'kunjungan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('kunjungan_s/read/$1'),'Read')." | ".anchor(site_url('kunjungan_s/update/$1'),'Update')." | ".anchor(site_url('kunjungan_s/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('tamu', $q);
	$this->db->or_like('jenis_tamu', $q);
	$this->db->or_like('waktu', $q);
	$this->db->or_like('foto', $q);
	$this->db->or_like('penerima_tamu', $q);
	$this->db->or_like('tujuan_kunjungan', $q);
	$this->db->or_like('no_hp_tamu', $q);
	$this->db->or_like('alamat_tamu', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('ket_tambahan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('tamu', $q);
	$this->db->or_like('jenis_tamu', $q);
	$this->db->or_like('waktu', $q);
	$this->db->or_like('foto', $q);
	$this->db->or_like('penerima_tamu', $q);
	$this->db->or_like('tujuan_kunjungan', $q);
	$this->db->or_like('no_hp_tamu', $q);
	$this->db->or_like('alamat_tamu', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('ket_tambahan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kunjungan_model_S.php */
/* Location: ./application/models/Kunjungan_model_S.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-04-28 06:43:15 */
/* http://harviacode.com */