<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Penerima_tamu_model extends CI_Model
{

    public $table = 'penerima_tamu';
    public $id_penerima = 'id_penerima';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id_penerima, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id_penerima
    function get_by_id($id_penerima)
    {
        $this->db->where($this->id_penerima, $id_penerima);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_penerima', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('nip', $q);
	$this->db->or_like('no_hp', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('gender', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id_penerima, $this->order);
        $this->db->like('id_penerima', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('nip', $q);
	$this->db->or_like('no_hp', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('gender', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id_penerima, $data)
    {
        $this->db->where($this->id_penerima, $id_penerima);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id_penerima)
    {
        $this->db->where($this->id_penerima, $id_penerima);
        $this->db->delete($this->table);
    }

}

/* End of file Penerima_tamu_model.php */
/* Location: ./application/models/Penerima_tamu_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-03-31 02:51:56 */
/* http://harviacode.com */